# Generated by Django 2.2 on 2019-05-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('transaction', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
