# Generated by Django 2.2.3 on 2019-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0005_auto_20190719_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationCodeToUsers',
        ),
        migrations.AlterField(
            model_name='usertoregistrationcode',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
